-- The scam registry.
--
-- Written as SQL rather than generated by an ORM because the constraints below
-- are the product. A publication rule enforced only in application code is a
-- publication rule that a future endpoint, a migration script or a psql session
-- can walk straight past, and what is at stake here is a public accusation
-- about a named person.

CREATE TABLE IF NOT EXISTS reports (
  id                  UUID PRIMARY KEY,

  -- Never returned to any client, in any role, including to the person
  -- reported. A reporter whose identity reaches the accused is a reporter who
  -- gets a visit, and after the first one nobody reports anything.
  reporter_id         TEXT        NOT NULL,

  -- Hashed. The registry answers about numbers it is asked; it does not hold a
  -- list of them to be stolen.
  reported_phone_hash TEXT        NOT NULL,

  status              TEXT        NOT NULL,
  category            TEXT        NOT NULL,
  description         TEXT        NOT NULL,
  evidence_keys       TEXT[]      NOT NULL DEFAULT '{}',

  submitted_at        TIMESTAMPTZ NOT NULL,
  reply_deadline_at   TIMESTAMPTZ NOT NULL,
  published_at        TIMESTAMPTZ,
  expires_at          TIMESTAMPTZ,

  has_reply           BOOLEAN     NOT NULL DEFAULT FALSE,
  reply               TEXT,

  -- The capability texted to the reported number. Random, never derivable from
  -- the id, and unique so a collision cannot hand one person another person's
  -- report.
  reply_token         TEXT        NOT NULL UNIQUE,

  CONSTRAINT reports_status_known CHECK (
    status IN (
      'submitted', 'under_review', 'awaiting_reply',
      'upheld', 'not_upheld', 'insufficient_evidence',
      'resolved', 'expired'
    )
  ),

  -- The rule the whole product rests on, in the schema.
  --
  -- `published_at` is the only column the public query filters on, so a row
  -- that carries one while not being upheld is a published accusation nobody
  -- decided to publish. The database refuses to store one.
  CONSTRAINT reports_only_upheld_is_published CHECK (
    published_at IS NULL OR status = 'upheld'
  ),

  -- Publication cannot precede the deadline the reported party was given,
  -- unless they answered early. `has_reply` is what makes the exception, and
  -- it is the same exception `review()` applies.
  CONSTRAINT reports_reply_window_respected CHECK (
    published_at IS NULL OR has_reply OR published_at >= reply_deadline_at
  ),

  -- A published report with nothing attached to it cannot have been assessed.
  CONSTRAINT reports_upheld_needs_evidence CHECK (
    published_at IS NULL OR cardinality(evidence_keys) > 0
  )
);

-- The public read: by phone, published only. A partial index, because the rows
-- that are not published are the majority and are never in this query.
CREATE INDEX IF NOT EXISTS reports_published_by_phone
  ON reports (reported_phone_hash)
  WHERE published_at IS NOT NULL;

-- The reviewer's queue.
CREATE INDEX IF NOT EXISTS reports_awaiting_decision
  ON reports (submitted_at)
  WHERE status IN ('submitted', 'under_review', 'awaiting_reply');

-- The retention sweep.
CREATE INDEX IF NOT EXISTS reports_expiring ON reports (expires_at)
  WHERE expires_at IS NOT NULL;
