/**
 * The wire, in one place.
 *
 * Three faces call this server: the renter and agent apps, the web surface,
 * and the review console. On the previous project the client sat inside the
 * mobile app for months, platform-free the whole time but reachable by only
 * one consumer, and moving it out later touched twenty-eight files. It starts
 * here as a package because we already know a second face is coming.
 *
 * ## Not written by hand
 *
 * `schema.ts` is generated by `openapi-typescript` from `openapi.json`, which
 * NestJS generates from the controllers' own decorators. Neither is edited.
 * `make api` regenerates both, and `scripts/api-fresh.sh` fails the build when
 * what is committed no longer matches what the controllers say — because a
 * client that is regenerated when somebody remembers is a client that is wrong.
 *
 * The functions below are the only hand-written part, and they hold no
 * knowledge of routes beyond the paths the generated types already name.
 */

import type { paths } from './schema.ts';

export type { paths };

export type Lookup =
  paths['/v1/registry/lookup']['get']['responses'][200]['content']['application/json'];
export type ReportAccepted =
  paths['/v1/registry/reports']['post']['responses'][201]['content']['application/json'];
export type SubmitReport =
  paths['/v1/registry/reports']['post']['requestBody']['content']['application/json'];
export type ReplyView =
  paths['/v1/registry/reply']['get']['responses'][200]['content']['application/json'];
export type SubmitReply =
  paths['/v1/registry/reply']['post']['requestBody']['content']['application/json'];
export type ReviewItem =
  paths['/v1/review/{id}']['get']['responses'][200]['content']['application/json'];
export type Decision =
  paths['/v1/review/{id}/decision']['post']['requestBody']['content']['application/json'];
export type DecisionMade =
  paths['/v1/review/{id}/decision']['post']['responses'][200]['content']['application/json'];

/**
 * What went wrong, in words a person can read.
 *
 * The server answers refusals with a `detail` written for the reader — the
 * reply window, the missing evidence — and losing that in favour of a status
 * code would leave the app inventing its own worse sentence.
 */
export class ApiError extends Error {
  constructor(
    readonly status: number,
    override readonly message: string,
    readonly refused?: string,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

export interface ClientOptions {
  readonly baseUrl: string;
  /** Present only in the review console. Absent everywhere else, by construction. */
  readonly reviewerToken?: string;
  readonly fetch?: typeof globalThis.fetch;
}

async function send<T>(
  options: ClientOptions,
  method: string,
  path: string,
  init: { query?: Record<string, string>; body?: unknown } = {},
): Promise<T> {
  const url = new URL(path, options.baseUrl);
  for (const [k, v] of Object.entries(init.query ?? {})) url.searchParams.set(k, v);

  const doFetch = options.fetch ?? globalThis.fetch;
  const response = await doFetch(url, {
    method,
    headers: {
      ...(init.body ? { 'content-type': 'application/json' } : {}),
      ...(options.reviewerToken ? { 'x-reviewer-token': options.reviewerToken } : {}),
    },
    ...(init.body ? { body: JSON.stringify(init.body) } : {}),
  });

  const text = await response.text();
  const parsed: unknown = text ? JSON.parse(text) : null;

  if (!response.ok) {
    const shape = parsed as { message?: string; detail?: string; refused?: string } | null;
    throw new ApiError(
      response.status,
      shape?.detail ?? shape?.message ?? 'That did not work. Try again.',
      shape?.refused,
    );
  }
  return parsed as T;
}

export function client(options: ClientOptions) {
  return {
    lookup: (phone: string) =>
      send<Lookup>(options, 'GET', '/v1/registry/lookup', { query: { phone } }),

    report: (body: SubmitReport) =>
      send<ReportAccepted>(options, 'POST', '/v1/registry/reports', { body }),

    /** The reported party's own view, by the token texted to their number. */
    reportAboutMe: (token: string) =>
      send<ReplyView>(options, 'GET', '/v1/registry/reply', { query: { token } }),

    answer: (body: SubmitReply) =>
      send<{ received: boolean; whatHappensNext: string }>(
        options,
        'POST',
        '/v1/registry/reply',
        { body },
      ),

    review: {
      queue: () => send<ReviewItem[]>(options, 'GET', '/v1/review/queue'),
      one: (id: string) => send<ReviewItem>(options, 'GET', `/v1/review/${id}`),
      decide: (id: string, body: Decision) =>
        send<DecisionMade>(options, 'POST', `/v1/review/${id}/decision`, { body }),
    },
  };
}

export type KeysClient = ReturnType<typeof client>;
