/**
 * The wire, in one place.
 *
 * Three faces call this server: the renter and agent apps, the web surface,
 * and the review console. On the previous project the client sat inside the
 * mobile app for months, platform-free the whole time but reachable by only
 * one consumer, and moving it out later touched twenty-eight files. It starts
 * here as a package because we already know a second face is coming.
 *
 * ## Not written by hand
 *
 * `schema.ts` is generated by `openapi-typescript` from `openapi.json`, which
 * NestJS generates from the controllers' own decorators. Neither is edited.
 * `make api` regenerates both, and `scripts/api-fresh.sh` fails the build when
 * what is committed no longer matches what the controllers say — because a
 * client that is regenerated when somebody remembers is a client that is wrong.
 *
 * The functions below are the only hand-written part, and they hold no
 * knowledge of routes beyond the paths the generated types already name.
 */

import type { paths } from './schema.ts';

export type { paths };

export type Lookup =
  paths['/v1/registry/lookup']['get']['responses'][200]['content']['application/json'];
export type ReportAccepted =
  paths['/v1/registry/reports']['post']['responses'][201]['content']['application/json'];
export type SubmitReport =
  paths['/v1/registry/reports']['post']['requestBody']['content']['application/json'];
export type ReplyView =
  paths['/v1/registry/reply']['get']['responses'][200]['content']['application/json'];
export type SubmitReply =
  paths['/v1/registry/reply']['post']['requestBody']['content']['application/json'];
export type AgentProfile =
  paths['/v1/agents']['get']['responses'][200]['content']['application/json'];
export type SignedUp =
  paths['/v1/agents']['post']['responses'][201]['content']['application/json'];
export type Listing =
  paths['/v1/agents/me/listings']['post']['responses'][201]['content']['application/json'];
export type ChallengeAnswered =
  paths['/v1/authority/confirm']['post']['responses'][200]['content']['application/json'];
export type ChallengeOpened =
  paths['/v1/authority/withdrawal']['post']['responses'][201]['content']['application/json'];
export type ReviewItem =
  paths['/v1/review/{id}']['get']['responses'][200]['content']['application/json'];
export type Decision =
  paths['/v1/review/{id}/decision']['post']['requestBody']['content']['application/json'];
export type DecisionMade =
  paths['/v1/review/{id}/decision']['post']['responses'][200]['content']['application/json'];
export type AgentUnderReview =
  paths['/v1/agent-review']['get']['responses'][200]['content']['application/json'][number];
export type ReviewMetrics =
  paths['/v1/review/metrics']['get']['responses'][200]['content']['application/json'];

/**
 * What went wrong, in words a person can read.
 *
 * The server answers refusals with a `detail` written for the reader — the
 * reply window, the missing evidence — and losing that in favour of a status
 * code would leave the app inventing its own worse sentence.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly refused: string | undefined;

  // Fields assigned in the body rather than declared as constructor parameter
  // properties: Node runs this package's tests by stripping types, and it
  // cannot strip a parameter property because the property only exists in the
  // types it is removing.
  constructor(status: number, message: string, refused?: string) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.refused = refused;
  }
}

/**
 * Why a request did not produce a value.
 *
 * `unreachable` and `refused` are kept apart all the way to the screen. A
 * phone with no signal has not been told anything, and rendering that as an
 * empty list tells somebody their reports do not exist when the truth is that
 * the app cannot see them. On a Nigerian network that distinction is the
 * difference between a working app and a lying one.
 */
export type ApiFailure =
  | { readonly kind: 'unreachable' }
  | {
      readonly kind: 'refused';
      readonly status: number;
      /** The server's own machine-readable reason, where it gave one. */
      readonly code: string | null;
      /** The server's own sentence, written for a reader. */
      readonly detail: string;
    };

export type ApiResult<T> =
  | { readonly ok: true; readonly value: T }
  | { readonly ok: false; readonly failure: ApiFailure };

/**
 * Turns a throwing call into a result.
 *
 * Two surfaces on one implementation. Server-side rendering wants exceptions,
 * because a page that cannot load should fail loudly and be caught once. A
 * phone wants a value, because "the network is down" is a state a screen
 * renders rather than an error a screen catches.
 */
export async function attempt<T>(run: () => Promise<T>): Promise<ApiResult<T>> {
  try {
    return { ok: true, value: await run() };
  } catch (error) {
    if (error instanceof ApiError) {
      return {
        ok: false,
        failure: {
          kind: 'refused',
          status: error.status,
          code: error.refused ?? null,
          detail: error.message,
        },
      };
    }
    // Anything that is not an answer from the server is a failure to reach it:
    // DNS, a dropped connection, an aborted fetch. None of them are refusals
    // and none of them mean the data is not there.
    return { ok: false, failure: { kind: 'unreachable' } };
  }
}

export interface ClientOptions {
  readonly baseUrl: string;
  /** Present only in the review console. Absent everywhere else, by construction. */
  readonly reviewerToken?: string;
  /**
   * The agent's own session. Present only on the agent surface's server side —
   * it is read out of an httpOnly cookie by a proxy, so no browser this token
   * belongs to can read it.
   */
  readonly agentToken?: string;
  readonly fetch?: typeof globalThis.fetch;
}

async function send<T>(
  options: ClientOptions,
  method: string,
  path: string,
  init: { query?: Record<string, string>; body?: unknown } = {},
): Promise<T> {
  const url = new URL(path, options.baseUrl);
  for (const [k, v] of Object.entries(init.query ?? {})) url.searchParams.set(k, v);

  const doFetch = options.fetch ?? globalThis.fetch;
  const response = await doFetch(url, {
    method,
    headers: {
      ...(init.body ? { 'content-type': 'application/json' } : {}),
      ...(options.reviewerToken ? { 'x-reviewer-token': options.reviewerToken } : {}),
      ...(options.agentToken ? { 'x-agent-token': options.agentToken } : {}),
    },
    ...(init.body ? { body: JSON.stringify(init.body) } : {}),
  });

  const text = await response.text();
  const parsed: unknown = text ? JSON.parse(text) : null;

  if (!response.ok) {
    const shape = parsed as { message?: string; detail?: string; refused?: string } | null;
    throw new ApiError(
      response.status,
      shape?.detail ?? shape?.message ?? 'That did not work. Try again.',
      shape?.refused,
    );
  }
  return parsed as T;
}

/**
 * The calls anything outside this package makes.
 *
 * The review console is deliberately absent. Its browser reaches the API
 * through a same-origin proxy that allow-lists paths, so the reviewer's token
 * never leaves the origin — which means the console cannot call these
 * functions, and a set of `review.*` methods lived here for a phase with no
 * caller anywhere. `wired-check` could not see it: the rule that looks for
 * exactly this was pointed at a path from the previous project.
 *
 * What the console does share is the *types*. It had hand-written copies of
 * the server's response shapes, which is the same duplication one level down.
 */
export function client(options: ClientOptions) {
  return {
    lookup: (phone: string) =>
      send<Lookup>(options, 'GET', '/v1/registry/lookup', { query: { phone } }),

    /**
     * The other half of the answer about a number.
     *
     * `lookup` says what has been held against it; this says what has been
     * confirmed about whoever trades under it. A screen showing only the first
     * tells a tenant what to fear and nothing about what to trust, and 404 is
     * the ordinary answer here — most numbers belong to nobody on Keys.
     */
    agentByPhone: (phone: string) =>
      send<AgentProfile>(options, 'GET', '/v1/agents', { query: { phone } }),

    /**
     * The agent's own calls.
     *
     * `signUp` is the only one reachable without a token, and it verifies
     * nothing — an account is a name and a phone number until a vendor has
     * checked an ID and a landlord has confirmed a property.
     */
    signUp: (displayName: string, phone: string) =>
      send<SignedUp>(options, 'POST', '/v1/agents', { body: { displayName, phone } }),

    agent: {
      me: () => send<AgentProfile>(options, 'GET', '/v1/agents/me'),

      askLandlord: (propertyId: string, landlordPhone: string) =>
        send<ChallengeOpened>(options, 'POST', '/v1/agents/me/authority', {
          body: { propertyId, landlordPhone },
        }),

      draft: (propertyId: string, title: string) =>
        send<Listing>(options, 'POST', '/v1/agents/me/listings', {
          body: { propertyId, title },
        }),

      publish: (id: string) =>
        send<Listing>(options, 'POST', `/v1/agents/me/listings/${id}/publish`),

      listings: () => send<Listing[]>(options, 'GET', '/v1/agents/me/listings'),
    },

    /** The landlord's two calls. No account, by design — see the controller. */
    confirmAuthority: (challengeId: string, code: string) =>
      send<ChallengeAnswered>(options, 'POST', '/v1/authority/confirm', {
        body: { challengeId, code },
      }),

    askToWithdrawAuthority: (agentId: string, propertyId: string) =>
      send<ChallengeOpened>(options, 'POST', '/v1/authority/withdrawal', {
        body: { agentId, propertyId },
      }),

    report: (body: SubmitReport) =>
      send<ReportAccepted>(options, 'POST', '/v1/registry/reports', { body }),

    /** The reported party's own view, by the token texted to their number. */
    reportAboutMe: (token: string) =>
      send<ReplyView>(options, 'GET', '/v1/registry/reply', { query: { token } }),

    answer: (body: SubmitReply) =>
      send<{ received: boolean; whatHappensNext: string }>(
        options,
        'POST',
        '/v1/registry/reply',
        { body },
      ),

  };
}

export type KeysClient = ReturnType<typeof client>;
