/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/registry/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is publicly known about a number. No account required. */
        get: operations["ReportsController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/transparency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the registry says about its own accuracy. Public, no account. */
        get: operations["ReportsController_transparency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a number. Nothing is published until a person reviews it. */
        post: operations["ReportsController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What was said about you. Requires the token texted to your number. */
        get: operations["ReplyController_show"];
        put?: never;
        /** Answer a report about your number. */
        post: operations["ReplyController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports awaiting a decision. */
        get: operations["ReviewController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the queue is doing. Phase 1 does not close until this is watched. */
        get: operations["ReviewController_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One report, in full, for review. */
        get: operations["ReviewController_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record evidence a reviewer obtained, with how it arrived. */
        post: operations["ReviewController_evidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide a report. The domain refuses what policy forbids. */
        post: operations["ReviewController_decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, and whether the store is durable. */
        get: operations["HealthController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether a number belongs to a verified agent. No account required. */
        get: operations["AgentsController_byPhone"];
        put?: never;
        /** Open an agent account. Verifies nothing on its own. */
        post: operations["AgentsController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own standing, computed from your evidence. */
        get: operations["AgentsController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is publicly known about an agent. No account required. */
        get: operations["AgentsController_publicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/authority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a landlord to confirm you may let a property. */
        post: operations["AgentsController_requestAuthority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your listings, drafts included. */
        get: operations["AgentsController_mine"];
        put?: never;
        /** Draft a listing. Drafts are private. */
        post: operations["AgentsController_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a listing. Needs a landlord confirmation on that property. */
        post: operations["AgentsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask for a code to withdraw an authority. Texted to the landlord who granted it. */
        post: operations["AuthorityController_askToWithdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a code from a text. Grants or withdraws, as the text said. */
        post: operations["AuthorityController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a completed identity check. Vendor only. */
        post: operations["AuthorityController_identity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/agents/{id}/withdraw-identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw an identity check. Unpublishes every listing that agent has. */
        post: operations["AgentReviewController_withdrawIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LookupResponse: {
            /** @description Always true. Present so that "we checked and found nothing" cannot be confused with "the request failed". */
            checked: boolean;
            /** @description Reports a person reviewed and upheld. Never a count of submissions. */
            upheldReports: number;
            categories: ("fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show")[];
            /** Format: date-time */
            mostRecent: string | null;
            /** @description False if any published report went unanswered within its reply window. */
            everyReportHadRightOfReply: boolean;
            /** @description Plain words for the reader. Zero upheld is not a clean bill of health. */
            meaning: string;
        };
        TransparencyResponse: {
            /** Format: date-time */
            since: string;
            /** @description Reports submitted in the window. */
            received: number;
            upheld: number;
            /** @description Dismissed or found to have insufficient evidence. The number nobody in this market publishes. */
            notUpheld: number;
            awaitingDecision: number;
            /** @description Median, not mean — one stalled case must not hide the typical wait. */
            medianDaysToDecision: number | null;
            oldestAwaitingDays: number | null;
        };
        SubmitReportBody: {
            /** @example +2348012345678 */
            reportedPhone: string;
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            /** @description A report nobody can assess cannot be upheld. */
            description: string;
            evidenceKeys?: string[];
        };
        ReportAcceptedResponse: {
            received: boolean;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** Format: date-time */
            replyDeadlineAt: string;
            whatHappensNext: string;
        };
        ReplyView: {
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            description: string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            replyBy: string;
            alreadyReplied: boolean;
            note: string;
        };
        SubmitReplyBody: {
            /** @description The token texted to the number that was reported. */
            token: string;
            reply: string;
        };
        ReviewView: {
            id: string;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            replyDeadlineAt: string;
            /** Format: date-time */
            publishedAt: string | null;
            description: string;
            evidenceCount: number;
            hasReply: boolean;
            reply: string | null;
        };
        ReviewerTally: {
            reviewer: string;
            /** @enum {string} */
            action: "upheld" | "not_upheld" | "insufficient_evidence" | "evidence_recorded";
            count: number;
        };
        ThroughputResponse: {
            /** Format: date-time */
            since: string;
            /** @description What each reviewer decided. Named, because "a reviewer" is not an answer to "who decided this". */
            decisions: components["schemas"]["ReviewerTally"][];
            /** @description Reports waiting. This is the constraint on how fast Keys can open a city. */
            waiting: number;
            /** Format: date-time */
            oldestWaitingSince: string | null;
        };
        EvidenceBody: {
            /** @description What the evidence was. A reviewer auditing this later reads exactly this. */
            note: string;
            /**
             * @description How it reached you. Phase 1 has no upload; phase 3 replaces this with files.
             * @example emailed screenshots
             */
            source: string;
        };
        DecisionBody: {
            /** @enum {string} */
            decision: "upheld" | "not_upheld" | "insufficient_evidence";
            /** @description Why. Mandatory: this is the audit record for a public claim about a named person, and somebody may have to answer for it a year from now. */
            reasoning: string;
        };
        DecisionResponse: {
            id: string;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** Format: date-time */
            publishedAt: string | null;
            /** @description Said out loud so a reviewer knows what they just did in public. */
            nowVisiblePublicly: boolean;
        };
        SignUpBody: {
            /** @example Chinedu Okafor */
            displayName: string;
            /** @example +2348012345678 */
            phone: string;
        };
        SignUpResponse: {
            agentId: string;
            /** @description Shown once. Keys does not store it, only its digest. */
            token: string;
        };
        AgentProfileResponse: {
            agentId: string;
            displayName: string;
            /**
             * @description Computed from evidence on every read. Not stored.
             * @enum {string}
             */
            tier: "unverified" | "identity" | "authority" | "established";
            /** @description What was actually checked, in words a tenant could go and verify. */
            meaning: string;
            /** @description Properties a landlord has confirmed they may let. */
            confirmedProperties: number;
            /** Format: date-time */
            joinedAt: string;
            /** @description Upheld scam reports against this agent. Zero is not a clean bill of health. */
            upheldReports: number;
        };
        AuthorityRequestBody: {
            /** @description The property this authority would cover. */
            propertyId: string;
            /**
             * @description The landlord's number. Not the agent's.
             * @example +2348012345678
             */
            landlordPhone: string;
        };
        ChallengeOpenedResponse: {
            /** @description Given to the landlord, not to the agent. */
            challengeId: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Whether the text could actually be sent yet. */
            delivered: boolean;
            whatHappensNext: string;
        };
        CreateListingBody: {
            propertyId: string;
            /** @example 2 bedroom flat, Yaba */
            title: string;
        };
        ListingResponse: {
            id: string;
            propertyId: string;
            title: string;
            /** Format: date-time */
            publishedAt: string | null;
        };
        AnswerChallengeBody: {
            challengeId: string;
            /**
             * @description The six digits from the text.
             * @example 049217
             */
            code: string;
        };
        ChallengeAnsweredResponse: {
            confirmed: boolean;
            /** @description True when the code withdrew an authority rather than granting one. */
            withdrawn: boolean;
            /** @description Listings that went dark as a result. Empty on a grant. */
            unpublishedListings: string[];
            meaning: string;
        };
        IdentityCheckBody: {
            /** @description The KYC vendor that ran the liveness and document check. */
            vendor: string;
            /** @description The vendor's own reference for the check, so it can be re-pulled. */
            reference: string;
            /** @description The agent the vendor checked. */
            agentId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ReportsController_lookup: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponse"];
                };
            };
        };
    };
    ReportsController_transparency: {
        parameters: {
            query: {
                sinceDays: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransparencyResponse"];
                };
            };
        };
    };
    ReportsController_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReportBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportAcceptedResponse"];
                };
            };
        };
    };
    ReplyController_show: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
        };
    };
    ReplyController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReplyBody"];
            };
        };
        responses: {
            /** @description The answer is on the record. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"][];
                };
            };
        };
    };
    ReviewController_metrics: {
        parameters: {
            query: {
                sinceDays: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputResponse"];
                };
            };
        };
    };
    ReviewController_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    ReviewController_evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    ReviewController_decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
        };
    };
    HealthController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentsController_byPhone: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileResponse"];
                };
            };
        };
    };
    AgentsController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUpResponse"];
                };
            };
        };
    };
    AgentsController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileResponse"];
                };
            };
        };
    };
    AgentsController_publicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileResponse"];
                };
            };
        };
    };
    AgentsController_requestAuthority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorityRequestBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOpenedResponse"];
                };
            };
        };
    };
    AgentsController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"][];
                };
            };
        };
    };
    AgentsController_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListingBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AgentsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AuthorityController_askToWithdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOpenedResponse"];
                };
            };
        };
    };
    AuthorityController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerChallengeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeAnsweredResponse"];
                };
            };
        };
    };
    AuthorityController_identity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityCheckBody"];
            };
        };
        responses: {
            /** @description The check was recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentReviewController_withdrawIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What went dark. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
