/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/registry/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is publicly known about a number. No account required. */
        get: operations["ReportsController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/transparency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the registry says about its own accuracy. Public, no account. */
        get: operations["ReportsController_transparency"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a number. Nothing is published until a person reviews it. */
        post: operations["ReportsController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What was said about you. Requires the token texted to your number. */
        get: operations["ReplyController_show"];
        put?: never;
        /** Answer a report about your number. */
        post: operations["ReplyController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports awaiting a decision. */
        get: operations["ReviewController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What the queue is doing. Phase 1 does not close until this is watched. */
        get: operations["ReviewController_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One report, in full, for review. */
        get: operations["ReviewController_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record evidence a reviewer obtained, with how it arrived. */
        post: operations["ReviewController_evidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide a report. The domain refuses what policy forbids. */
        post: operations["ReviewController_decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, and whether the store is durable. */
        get: operations["HealthController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whether a number belongs to a verified agent. No account required. */
        get: operations["AgentsController_byPhone"];
        put?: never;
        /** Open an agent account. Verifies nothing on its own. */
        post: operations["AgentsController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your own standing, computed from your evidence. */
        get: operations["AgentsController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is publicly known about an agent. No account required. */
        get: operations["AgentsController_publicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/authority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a landlord to confirm you may let a property. */
        post: operations["AgentsController_requestAuthority"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your listings, with what each still needs to be Verified. */
        get: operations["AgentsController_mine"];
        put?: never;
        /** Draft a listing. Drafts are private. */
        post: operations["AgentsController_draft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings/{id}/costs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Say what a listing costs to move into. All five figures, zeroes included. */
        post: operations["AgentsController_costs"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings/{id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish a listing. Needs a landlord confirmation on that property. */
        post: operations["AgentsController_publish"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings/{id}/place": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record where a property is, from standing at it. Once. */
        post: operations["AgentsController_place"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/me/listings/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Say a listing is still available. Verified listings expire without this. */
        post: operations["AgentsController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/withdrawal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask for a code to withdraw an authority. Texted to the landlord who granted it. */
        post: operations["AuthorityController_askToWithdraw"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Answer a code from a text. Grants or withdraws, as the text said. */
        post: operations["AuthorityController_confirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a completed identity check. Vendor only. */
        post: operations["AuthorityController_identity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every agent, with what has been attested about them. */
        get: operations["AgentReviewController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent-review/{id}/withdraw-identity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Withdraw an identity check. Unpublishes every listing that agent has. */
        post: operations["AgentReviewController_withdrawIdentity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Published listings, Verified first. No account required. */
        get: operations["SearchController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One listing, with what was actually checked about it. */
        get: operations["SearchController_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/listings/{id}/media/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A photograph from a published listing. No account required. */
        get: operations["SearchController_photograph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tenants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Open a tenant account. Needed to message an agent. */
        post: operations["MarketController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Your conversations. */
        get: operations["MarketController_mine"];
        put?: never;
        /** Ask an agent about a listing, without giving them your number. */
        post: operations["MarketController_open"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MarketController_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MarketController_saySomething"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{id}/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer your number. They see it only if they offer theirs. */
        post: operations["MarketController_offerAsTenant"];
        /** Take back a number they have not answered. */
        delete: operations["MarketController_unofferAsTenant"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/conversations/{id}/contact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Offer your number. They see it only if they offer theirs. */
        post: operations["MarketController_offerAsAgent"];
        /** Take back a number they have not answered. */
        delete: operations["MarketController_unofferAsAgent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People asking about your listings. */
        get: operations["MarketController_theirs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/conversations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MarketController_oneOfMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/conversations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MarketController_replyAsAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MarketController_myInspections"];
        put?: never;
        /** Ask to see the place. */
        post: operations["MarketController_ask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/inspections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MarketController_inspectionsOnMine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agent/inspections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agree to show it, and say what you will charge. */
        post: operations["MarketController_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/inspections/{id}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Say what happened. "It was not there" suspends the badge. */
        post: operations["MarketController_outcome"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register this phone's public key. Once per device. */
        post: operations["CapturesController_registerDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/captures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a signed capture. Unsigned uploads are refused. */
        post: operations["CapturesController_submit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/duplicates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Image matches waiting for a person. Closest first. */
        get: operations["DuplicatesController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/duplicates/{listingId}/{matchedListingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block the copy, or allow both. Needs a reason either way. */
        post: operations["DuplicatesController_decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LookupResponse: {
            /** @description Always true. Present so that "we checked and found nothing" cannot be confused with "the request failed". */
            checked: boolean;
            /** @description Reports a person reviewed and upheld. Never a count of submissions. */
            upheldReports: number;
            categories: ("fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show")[];
            /** Format: date-time */
            mostRecent: string | null;
            /** @description False if any published report went unanswered within its reply window. */
            everyReportHadRightOfReply: boolean;
            /** @description Plain words for the reader. Zero upheld is not a clean bill of health. */
            meaning: string;
        };
        TransparencyResponse: {
            /** Format: date-time */
            since: string;
            /** @description Reports submitted in the window. */
            received: number;
            upheld: number;
            /** @description Dismissed or found to have insufficient evidence. The number nobody in this market publishes. */
            notUpheld: number;
            awaitingDecision: number;
            /** @description Median, not mean — one stalled case must not hide the typical wait. */
            medianDaysToDecision: number | null;
            oldestAwaitingDays: number | null;
        };
        SubmitReportBody: {
            /**
             * @description The number you are reporting. Not needed — and not asked for — when you report a listing.
             * @example +2348012345678
             */
            reportedPhone?: string;
            /** @description The listing you are reporting. Keys resolves whose it is; you never need the agent's number, which is the whole point of holding numbers back until both sides agree. */
            listingId?: string;
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            /** @description A report nobody can assess cannot be upheld. */
            description: string;
            evidenceKeys?: string[];
        };
        ReportAcceptedResponse: {
            received: boolean;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** Format: date-time */
            replyDeadlineAt: string;
            whatHappensNext: string;
        };
        ReplyView: {
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            description: string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            replyBy: string;
            alreadyReplied: boolean;
            note: string;
        };
        SubmitReplyBody: {
            /** @description The token texted to the number that was reported. */
            token: string;
            reply: string;
        };
        ReviewView: {
            id: string;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            replyDeadlineAt: string;
            /** Format: date-time */
            publishedAt: string | null;
            description: string;
            evidenceCount: number;
            hasReply: boolean;
            reply: string | null;
            /** @description The listing this is about, when there is one. Null for a report that came in from the registry — a number and no property. A reviewer judging whether a place is fiction needs to be able to open it. */
            listingId: string | null;
        };
        ReviewerTally: {
            reviewer: string;
            /** @enum {string} */
            action: "upheld" | "not_upheld" | "insufficient_evidence" | "evidence_recorded";
            count: number;
        };
        ThroughputResponse: {
            /** Format: date-time */
            since: string;
            /** @description What each reviewer decided. Named, because "a reviewer" is not an answer to "who decided this". */
            decisions: components["schemas"]["ReviewerTally"][];
            /** @description Reports waiting. This is the constraint on how fast Keys can open a city. */
            waiting: number;
            /** Format: date-time */
            oldestWaitingSince: string | null;
        };
        EvidenceBody: {
            /** @description What the evidence was. A reviewer auditing this later reads exactly this. */
            note: string;
            /**
             * @description How it reached you. Phase 1 has no upload; phase 3 replaces this with files.
             * @example emailed screenshots
             */
            source: string;
        };
        DecisionBody: {
            /** @enum {string} */
            decision: "upheld" | "not_upheld" | "insufficient_evidence";
            /** @description Why. Mandatory: this is the audit record for a public claim about a named person, and somebody may have to answer for it a year from now. */
            reasoning: string;
        };
        DecisionResponse: {
            id: string;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** Format: date-time */
            publishedAt: string | null;
            /** @description Said out loud so a reviewer knows what they just did in public. */
            nowVisiblePublicly: boolean;
        };
        SignUpBody: {
            /** @example Chinedu Okafor */
            displayName: string;
            /** @example +2348012345678 */
            phone: string;
        };
        SignUpResponse: {
            agentId: string;
            /** @description Shown once. Keys does not store it, only its digest. */
            token: string;
        };
        AgentProfileResponse: {
            agentId: string;
            displayName: string;
            /**
             * @description Computed from evidence on every read. Not stored.
             * @enum {string}
             */
            tier: "unverified" | "identity" | "authority" | "established";
            /** @description What was actually checked, in words a tenant could go and verify. */
            meaning: string;
            /** @description Properties a landlord has confirmed they may let. */
            confirmedProperties: number;
            /** Format: date-time */
            joinedAt: string;
            /** @description Upheld scam reports against this agent. Zero is not a clean bill of health. */
            upheldReports: number;
        };
        AuthorityRequestBody: {
            /** @description The property this authority would cover. */
            propertyId: string;
            /**
             * @description The landlord's number. Not the agent's.
             * @example +2348012345678
             */
            landlordPhone: string;
        };
        ChallengeOpenedResponse: {
            /** @description Given to the landlord, not to the agent. */
            challengeId: string;
            /** Format: date-time */
            expiresAt: string;
            /** @description Whether the text could actually be sent yet. */
            delivered: boolean;
            whatHappensNext: string;
        };
        CostsBody: {
            /**
             * @description Rent for the year, in kobo.
             * @example 80000000
             */
            annualRentKobo: number;
            /**
             * @description The agent fee. Zero is an answer.
             * @example 8000000
             */
            agencyFeeKobo: number;
            /**
             * @description Preparing the tenancy agreement.
             * @example 8000000
             */
            legalFeeKobo: number;
            /**
             * @description Refundable at the end, payable on the day.
             * @example 10000000
             */
            cautionDepositKobo: number;
            /**
             * @description Service charge, where a building has one.
             * @example 4000000
             */
            serviceChargeKobo: number;
        };
        CreateListingBody: {
            propertyId: string;
            /** @example 2 bedroom flat, Yaba */
            title: string;
            /** @description Where the property is. Optional at draft, needed before a capture can prove presence. */
            latitude: number | null;
            longitude: number | null;
            /** @description What it costs. Optional at draft, needed before publication. Null is not the same as all zeroes: one is silence, the other is a claim. */
            costs: components["schemas"]["CostsBody"] | null;
        };
        StillNeeded: {
            /** @enum {string} */
            condition: "agent_identity" | "landlord_authority" | "capture_on_site" | "walkthrough_video" | "not_a_known_duplicate" | "recently_confirmed" | "nothing_upheld" | "costs_stated" | "nobody_found_it_missing";
            /** @description A sentence with a next action in it, not a failure notice. */
            whatToDo: string;
        };
        CostsResponse: {
            /**
             * @description Rent for the year, in kobo.
             * @example 80000000
             */
            annualRentKobo: number;
            /**
             * @description The agent fee. Zero is an answer.
             * @example 8000000
             */
            agencyFeeKobo: number;
            /**
             * @description Preparing the tenancy agreement.
             * @example 8000000
             */
            legalFeeKobo: number;
            /**
             * @description Refundable at the end, payable on the day.
             * @example 10000000
             */
            cautionDepositKobo: number;
            /**
             * @description Service charge, where a building has one.
             * @example 4000000
             */
            serviceChargeKobo: number;
            /** @description Everything payable before keys change hands, deposit included. */
            moveInKobo: number;
            /** @description What is on top of the advertised rent. The surprise, named. */
            extrasKobo: number;
            /** @description The agency fee as a percentage of rent. Ten is customary; this says when it is not. */
            agencyFeePercent: number | null;
            legalFeePercent: number | null;
        };
        ListingResponse: {
            id: string;
            propertyId: string;
            title: string;
            /** Format: date-time */
            publishedAt: string | null;
            /**
             * Format: date-time
             * @description When somebody last said this is still available. Null means never.
             */
            confirmedAt: string | null;
            /** @description Whether the property has coordinates. Captures cannot prove presence without them. */
            placed: boolean;
            /** @description Which of the eight Verified conditions are unmet, and what to do. Empty means Verified. */
            stillNeeded: components["schemas"]["StillNeeded"][];
            /** @description Null if the agent has not said. */
            costs: components["schemas"]["CostsResponse"] | null;
        };
        AnswerChallengeBody: {
            challengeId: string;
            /**
             * @description The six digits from the text.
             * @example 049217
             */
            code: string;
        };
        ChallengeAnsweredResponse: {
            confirmed: boolean;
            /** @description True when the code withdrew an authority rather than granting one. */
            withdrawn: boolean;
            /** @description Listings that went dark as a result. Empty on a grant. */
            unpublishedListings: string[];
            meaning: string;
        };
        IdentityCheckBody: {
            /** @description The KYC vendor that ran the liveness and document check. */
            vendor: string;
            /** @description The vendor's own reference for the check, so it can be re-pulled. */
            reference: string;
            /** @description The agent the vendor checked. */
            agentId: string;
        };
        AttestationView: {
            /** @enum {string} */
            kind: "identity" | "authority" | "standing";
            /** @description Who attested. Never a landlord's phone number. */
            attestor: string;
            propertyId: string | null;
            /** Format: date-time */
            at: string;
            /** @description False once withdrawn. Withdrawn evidence is kept, not deleted. */
            live: boolean;
        };
        AgentUnderReview: {
            agentId: string;
            displayName: string;
            /** @enum {string} */
            tier: "unverified" | "identity" | "authority" | "established";
            meaning: string;
            /** Format: date-time */
            joinedAt: string;
            upheldReports: number;
            publishedListings: number;
            evidence: components["schemas"]["AttestationView"][];
        };
        SearchResult: {
            id: string;
            title: string;
            address: string;
            /** @description Computed on every search from evidence. Never a stored column. */
            verified: boolean;
            agentName: string;
            /** @description Everything payable before keys change hands, in kobo. The comparable number — two listings advertising the same rent are not the same price, and a list showing only rent hides that. */
            moveInKobo: number | null;
            /** @description Rent alone, in kobo. Sent beside the total so a reader can see the gap for themselves. */
            annualRentKobo: number | null;
            /** @description Why this is ranked where it is. Said out loud, because a ranking nobody can interrogate is one somebody will assume was bought. */
            because: string[];
            /**
             * Format: date-time
             * @description When this listing's paid placement runs out, or null. Sent so a client can label the band without a second request, and so that a reader poking at the API sees the same fact the page shows.
             */
            featuredUntil: string | null;
        };
        SearchResponse: {
            /** @description Slots somebody paid for. Verified only, capped, and always drawn from listings this search already returned — a paid slot cannot show you a place you did not ask about. Usually empty. */
            featured: components["schemas"]["SearchResult"][];
            /** @description The answer to what was asked, ranked. Nothing in this list was bought, and anything in `featured` has been taken out of it so nobody appears twice. */
            results: components["schemas"]["SearchResult"][];
        };
        ListingCheck: {
            /** @enum {string} */
            condition: "agent_identity" | "landlord_authority" | "capture_on_site" | "walkthrough_video" | "not_a_known_duplicate" | "recently_confirmed" | "nothing_upheld" | "costs_stated" | "nobody_found_it_missing";
            /** @description The condition as a checklist row, in the reader's language. */
            label: string;
            met: boolean;
        };
        ListingView: {
            id: string;
            title: string;
            address: string;
            verified: boolean;
            agentName: string;
            /** @description What was checked about the agent, in words a tenant could verify. */
            agentMeaning: string;
            /** @description Every condition, met or not. Not a badge and not a score: the list of things that were checked, which a tenant can read and disagree with. */
            checks: components["schemas"]["ListingCheck"][];
            /** @description Null when the agent has not said, which is itself an unmet condition rather than a blank in the page. */
            costs: components["schemas"]["CostsResponse"] | null;
        };
        TenantSignUpBody: {
            /** @example Ada */
            displayName: string;
            /** @example +2348012345678 */
            phone: string;
        };
        TenantSignUpResponse: {
            tenantId: string;
            /** @description Shown once. Keys keeps a digest and cannot return it again — see the release gates for where a client must put it. */
            token: string;
        };
        OpenConversationBody: {
            listingId: string;
            /** @description The first thing to say. A conversation with nothing in it is not one. */
            body: string;
        };
        MessageResponse: {
            id: string;
            /** @enum {string} */
            speaker: "tenant" | "agent" | "keys";
            body: string;
            /** Format: date-time */
            sentAt: string;
        };
        ConversationResponse: {
            id: string;
            listingId: string;
            listingTitle: string;
            /** @description Who you are talking to. A name, never a number. */
            otherPartyName: string;
            /** @enum {string} */
            exchange: "none" | "tenant_offered" | "agent_offered" | "exchanged";
            /** @description The other party's number, and only once both of you have offered. Null at every other point, on every route, for everyone. */
            theirContact: string | null;
            messages: components["schemas"]["MessageResponse"][];
        };
        SayBody: {
            body: string;
        };
        OfferContactBody: {
            /**
             * @description The number you are choosing to share, here, with this person. Not read from your account — this product stores those as hashes, and a number that has to be revealed belongs only where revealing it is the point.
             * @example +2348012345678
             */
            contact: string;
        };
        RequestInspectionBody: {
            conversationId: string;
        };
        InspectionResponse: {
            id: string;
            listingId: string;
            listingTitle: string;
            /** @enum {string} */
            state: "requested" | "agreed" | "declined" | "done";
            /** @description What the agent said they would charge, in kobo. */
            feeKobo: number;
            /** @enum {string|null} */
            outcome: "did_not_exist" | "agent_did_not_show" | "asked_for_more_money" | "as_described" | "not_for_me" | null;
        };
        AnswerInspectionBody: {
            /** @description Agree to show it, or decline. */
            agreed: boolean;
            /**
             * @description What you will charge to show it, in kobo. Zero is an answer and a claim: a tenant who is then asked for money at the door can report it.
             * @example 0
             */
            feeKobo: number;
        };
        OutcomeBody: {
            /** @enum {string} */
            outcome: "did_not_exist" | "agent_did_not_show" | "asked_for_more_money" | "as_described" | "not_for_me";
            /** @description What you were actually asked for at the door, in kobo. Required when the outcome is asked_for_more_money, and checked against what the agent declared — a complaint its own figures contradict is refused rather than filed. */
            paidKobo?: number | null;
        };
        RegisterDeviceBody: {
            /** @description The device's P-256 public key, SPKI DER, base64. P-256 because that is what the Secure Enclave holds. */
            publicKey: string;
        };
        CaptureBody: {
            deviceId: string;
            listingId: string;
            /** @description SHA-256 of the media bytes — the photograph or the video — lower-case hex. When no media is sent this is the grid, as it was before real photographs existed. */
            sha256: string;
            /** @description SHA-256 of the greyscale grid. Inside the signature alongside the media hash, because the grid is what duplicate detection reads — a grid outside the signature is a grid an agent can invent, and a stolen photograph would arrive matching nothing. */
            gridSha256?: string | null;
            /** @description The photograph or video itself, base64. Optional while there is no camera on a simulator; what is not optional is that it hashes to the sha256 inside the signature. */
            media?: string;
            /** Format: date-time */
            capturedAt: string;
            latitude: number;
            longitude: number;
            /** @description Once per capture. A reused one is refused. */
            nonce: string;
            /** @description What the OS said about the location. Signed, so it cannot be flipped. */
            mockLocation: boolean;
            /** @enum {string} */
            kind: "photo" | "video";
            durationSeconds: number | null;
            /** @description ECDSA P-256 over SHA-256 of the canonical claim, DER, base64. */
            signature: string;
            /** @description The capture itself: a Keys greyscale grid, base64. Its SHA-256 must be the one inside the signature. */
            pixels: string;
        };
        CaptureRefusedResponse: {
            accepted: boolean;
            refusals: ("unknown_device" | "not_this_agents_device" | "bad_signature" | "bytes_do_not_match" | "replayed" | "stale" | "from_the_future" | "mock_location")[];
            /** @description One sentence per refusal, written for the agent. */
            meaning: string[];
            /**
             * @description Never "blocked" here. A match opens a review; a person decides.
             * @enum {string}
             */
            duplicates: "blocked" | "allowed" | "pending";
            /** @description Listings this image resembles. */
            looksLikeListings: string[];
        };
        DuplicatePairView: {
            /** @description The listing that uploaded the picture second. */
            listingId: string;
            /** @description The listing that already had it. */
            matchedListingId: string;
            /** @description Differing bits, out of 64. Zero is the same file. */
            distance: number;
            /** Format: date-time */
            firstSeenAt: string;
            /** @description What the distance means, in words a reviewer can act on. */
            meaning: string;
        };
        DuplicateDecisionBody: {
            /** @enum {string} */
            decision: "blocked" | "allowed";
            /** @description Mandatory. This is the audit record. */
            reasoning: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ReportsController_lookup: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponse"];
                };
            };
        };
    };
    ReportsController_transparency: {
        parameters: {
            query: {
                sinceDays: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransparencyResponse"];
                };
            };
        };
    };
    ReportsController_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReportBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportAcceptedResponse"];
                };
            };
        };
    };
    ReplyController_show: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
        };
    };
    ReplyController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReplyBody"];
            };
        };
        responses: {
            /** @description The answer is on the record. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"][];
                };
            };
        };
    };
    ReviewController_metrics: {
        parameters: {
            query: {
                sinceDays: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThroughputResponse"];
                };
            };
        };
    };
    ReviewController_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    ReviewController_evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    ReviewController_decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
        };
    };
    HealthController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentsController_byPhone: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileResponse"];
                };
            };
        };
    };
    AgentsController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignUpResponse"];
                };
            };
        };
    };
    AgentsController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileResponse"];
                };
            };
        };
    };
    AgentsController_publicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileResponse"];
                };
            };
        };
    };
    AgentsController_requestAuthority: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorityRequestBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOpenedResponse"];
                };
            };
        };
    };
    AgentsController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"][];
                };
            };
        };
    };
    AgentsController_draft: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateListingBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AgentsController_costs: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CostsBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AgentsController_publish: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AgentsController_place: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AgentsController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingResponse"];
                };
            };
        };
    };
    AuthorityController_askToWithdraw: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeOpenedResponse"];
                };
            };
        };
    };
    AuthorityController_confirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerChallengeBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChallengeAnsweredResponse"];
                };
            };
        };
    };
    AuthorityController_identity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentityCheckBody"];
            };
        };
        responses: {
            /** @description The check was recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AgentReviewController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentUnderReview"][];
                };
            };
        };
    };
    AgentReviewController_withdrawIdentity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description What went dark. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SearchController_search: {
        parameters: {
            query: {
                q: string;
                latitude: string;
                longitude: string;
                verifiedOnly: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
    SearchController_one: {
        parameters: {
            query: {
                language: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingView"];
                };
            };
        };
    };
    SearchController_photograph: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MarketController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TenantSignUpBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantSignUpResponse"];
                };
            };
        };
    };
    MarketController_mine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"][];
                };
            };
        };
    };
    MarketController_open: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenConversationBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_saySomething: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SayBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_offerAsTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferContactBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_unofferAsTenant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_offerAsAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OfferContactBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_unofferAsAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_theirs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"][];
                };
            };
        };
    };
    MarketController_oneOfMine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_replyAsAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SayBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
        };
    };
    MarketController_myInspections: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"][];
                };
            };
        };
    };
    MarketController_ask: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestInspectionBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
        };
    };
    MarketController_inspectionsOnMine: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"][];
                };
            };
        };
    };
    MarketController_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerInspectionBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
        };
    };
    MarketController_outcome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OutcomeBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InspectionResponse"];
                };
            };
        };
    };
    CapturesController_registerDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDeviceBody"];
            };
        };
        responses: {
            /** @description The device id to sign captures with. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CapturesController_submit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaptureBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaptureRefusedResponse"];
                };
            };
        };
    };
    DuplicatesController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicatePairView"][];
                };
            };
        };
    };
    DuplicatesController_decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                listingId: string;
                matchedListingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateDecisionBody"];
            };
        };
        responses: {
            /** @description What was decided. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
