/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/registry/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What is publicly known about a number. No account required. */
        get: operations["ReportsController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report a number. Nothing is published until a person reviews it. */
        post: operations["ReportsController_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/registry/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What was said about you. Requires the token texted to your number. */
        get: operations["ReplyController_show"];
        put?: never;
        /** Answer a report about your number. */
        post: operations["ReplyController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reports awaiting a decision. */
        get: operations["ReviewController_queue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One report, in full, for review. */
        get: operations["ReviewController_one"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record evidence a reviewer obtained, with how it arrived. */
        post: operations["ReviewController_evidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/review/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide a report. The domain refuses what policy forbids. */
        post: operations["ReviewController_decide"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness, and whether the store is durable. */
        get: operations["HealthController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LookupResponse: {
            /** @description Always true. Present so that "we checked and found nothing" cannot be confused with "the request failed". */
            checked: boolean;
            /** @description Reports a person reviewed and upheld. Never a count of submissions. */
            upheldReports: number;
            categories: ("fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show")[];
            /** Format: date-time */
            mostRecent: string | null;
            /** @description False if any published report went unanswered within its reply window. */
            everyReportHadRightOfReply: boolean;
            /** @description Plain words for the reader. Zero upheld is not a clean bill of health. */
            meaning: string;
        };
        SubmitReportBody: {
            /** @example +2348012345678 */
            reportedPhone: string;
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            /** @description A report nobody can assess cannot be upheld. */
            description: string;
            evidenceKeys?: string[];
        };
        ReportAcceptedResponse: {
            received: boolean;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** Format: date-time */
            replyDeadlineAt: string;
            whatHappensNext: string;
        };
        ReplyView: {
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            description: string;
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            replyBy: string;
            alreadyReplied: boolean;
            note: string;
        };
        SubmitReplyBody: {
            /** @description The token texted to the number that was reported. */
            token: string;
            reply: string;
        };
        ReviewView: {
            id: string;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** @enum {string} */
            category: "fake_listing" | "inspection_fee_scam" | "property_already_let" | "impersonation" | "undisclosed_fees" | "no_show";
            /** Format: date-time */
            submittedAt: string;
            /** Format: date-time */
            replyDeadlineAt: string;
            /** Format: date-time */
            publishedAt: string | null;
            description: string;
            evidenceCount: number;
            hasReply: boolean;
            reply: string | null;
        };
        EvidenceBody: {
            /** @description What the evidence was. A reviewer auditing this later reads exactly this. */
            note: string;
            /**
             * @description How it reached you. Phase 1 has no upload; phase 3 replaces this with files.
             * @example emailed screenshots
             */
            source: string;
        };
        DecisionBody: {
            /** @enum {string} */
            decision: "upheld" | "not_upheld" | "insufficient_evidence";
        };
        DecisionResponse: {
            id: string;
            /** @enum {string} */
            status: "submitted" | "under_review" | "awaiting_reply" | "upheld" | "not_upheld" | "insufficient_evidence" | "resolved" | "expired";
            /** Format: date-time */
            publishedAt: string | null;
            /** @description Said out loud so a reviewer knows what they just did in public. */
            nowVisiblePublicly: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ReportsController_lookup: {
        parameters: {
            query: {
                phone: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LookupResponse"];
                };
            };
        };
    };
    ReportsController_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReportBody"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportAcceptedResponse"];
                };
            };
        };
    };
    ReplyController_show: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyView"];
                };
            };
        };
    };
    ReplyController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitReplyBody"];
            };
        };
        responses: {
            /** @description The answer is on the record. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ReviewController_queue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"][];
                };
            };
        };
    };
    ReviewController_one: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    ReviewController_evidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewView"];
                };
            };
        };
    };
    ReviewController_decide: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionBody"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
        };
    };
    HealthController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
